apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  labels:
    app: web
spec:
  containers:
    - name: api
      image: revgoproject3/api
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  labels:
    app: web
spec:
  containers:
    - name: client
      image: revgoproject3/client
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  labels:
    app: web
spec:
  containers:
    - name: slackbot
      image: revgoproject3/slackbot
      ports:
        - containerPort: 80
