apiVersion: app/v1
kind: Deployment
metadata:
  name: revgoclient
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: revgoclient
    spec:
      containers:
      - name: revgoclient
        image: revgoproject3/client
metadata:
  name: revgoslackbot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: revgoslackbot
    spec:
      containers:
      - name: revgoslackbot
        image: revgoproject3/slackbot
