apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: revgo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: revgoclient
    spec:
      containers:
      - name: revgoclient
        image: revgoproject3/client
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: revgo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: revgoslackbot
    spec:
      containers:
      - name: revgoslackbot
        image: revgoproject3/slackbot
